[package]
name = "mandelrust"
version = "0.1.0"
authors = ["André-Patrick Bubel <code@andre-bubel.de>"]
license = "GPL-3.0+"

[dependencies]
rust-mpfr = "*"
timeit = "*"
image = "*"
pbr = "*"
palette = "*"
carboxyl = "*"
